### ISSUE TITLE
Support for multiple different cells for same model object?

### ISSUE THREAD

**Issue by markst** [DenHeadless/DTTableViewManager#19]
I have model object which I wish to display a different group of cells depending on the state of the object. 
Something like the following:
```objc
    [self registerCellClass:[FirstCell class]
              forModelClass:[CustomModel class]];

    [self registerCellClass:[SecondCell class]
              forModelClass:[CustomModel class]];

    [self registerCellClass:[Relationship class]
              forModelClass:[CustomModel class]];
    
    [[self memoryStorage] addItem:object];

    if (object.numberOfFriends > 0) {
        for (NSInteger idx = 0; i < object.numberOfFriends; idx ++ ) {
            [[self memoryStorage] addItem:object.friends[idx]];
        }
    }
```

**Comment by DenHeadless** [comment]
Hi! 

Recently i've been playing with this idea of models, that define which cell class they should use depending on inner state, but it didn't work out very well. It was really cumbersome and put a lot of knowledge about cells to a model layer. 

Instead of going with this, i chose to use MVVM pattern, that worked out great. In your example, i would make three more view models, mapping them to cells like this

```
[self registerCellClass:[FirstCell class] forModelClass:[CustomViewModel1 class]];
[self registerCellClass:[SecondCell class] forModelClass:[CustomViewModel2 class]];
...e.t.c.
```

I would make a category on CustomModel, that knows, which view model should be created from your original model. 

This approach allows you to pass to view models only that properties, that should be displayed. It also allows view-models to be easily unit-tested. And while adding three more classes to your setup, it actually makes your code much cleaner.
