### ISSUE TITLE
Memory storage moveTableItemAtIndexPath:toIndexPath: bug

### ISSUE THREAD

**Issue by orkenstein** [DenHeadless/DTTableViewManager#21]
When moving to the last row, content offset changes incorrectly:
![untitled](https://cloud.githubusercontent.com/assets/1461936/6708521/1d9b151a-cd82-11e4-8ea0-3c2f93a6d7a0.gif)

**Comment by DenHeadless** [comment]
This is probably UITableView/UIScrollView bug. DTTableViewManager does not contain any code, that influences layout, specifically content offsets.

[This code](https://github.com/DenHeadless/DTTableViewManager/blob/master/DTTableViewManager/DTTableViewController.m#L457-L474) is called, if you use default UITableView reordering behaviour. Using this method is usually what you want if reordering is initiated by user.

And [this method](https://github.com/DenHeadless/DTTableViewManager/blob/master/DTTableViewManager/DTMemoryStorage_DTTableViewManagerAdditions.m#L69-L108) is usually good, when reordering is initiated by programmer.

I'm closing this issue for now, because it seems framework has nothing to do with this. 

Please let me know if i can help you more on this issue, or reopen, if you think there are things we can do from framework standpoint.
