### ISSUE TITLE
Implement table view controller without xib or storyboard

### ISSUE THREAD

**Issue by AlexEdunov** [DenHeadless/DTTableViewManager#22]
> Subclass DTTableViewController, create xib, or storyboard with your view controller, wire up tableView outlet.

Is it possible to implement table view controller without xib or storyboard using this project?

**Comment by DenHeadless** [comment]
No, creating table view controller from code is not supported due to the nature of cell registration from storyboards - this was a simple choice between storyboards and plain code. Obviously, storyboards won.

It probably does work, but you have to call registerClass:forCellReuseIdentifier: yourself, because built-in register methods will not work.
