### ISSUE TITLE
AddItems: function signature.

### ISSUE THREAD

**Issue by orkenstein** [DenHeadless/DTTableViewManager#31]
The function is declared as:
```
    public func addItems<T>(items: [T], toSection index: Int = 0)
```
So we're unable to pass array of different models. They all have to be the same class. Probably the function might be declared as:
```
    public func addItems(items: [AnyObject], toSection index: Int = 0)
```

**Comment by DenHeadless** [comment]
That is not exactly true, because array of different types can be inferred by Swift as [AnyObject] or [Any].  In worst case scenario, you could always use flatMap:

```swift
addItems(items.flatMap { $0 as? AnyObject })
```
That's, of course, not ideal, as it really should be declared not as [T], but as [Any], to support both reference and value types. Unfortunately, if you make items variable [Any] type, it will simply crash an application with following error:

```swift
fatal error: array cannot be bridged from Objective-C
```

This behaviour can be easily reproduced in DTModelStorage test suit. I will monitor changes to Swift language in 2.2 and 3.0 releases, as I want to make those variables of type [Any], however right now it's not possible.
