### ISSUE TITLE
Proposal: allow look up for header class in storyboard.

### ISSUE THREAD

**Issue by orkenstein** [DenHeadless/DTTableViewManager#35]
Current implementation does not allow to register `UITableView` header to `UITableViewCell` prototyped in storyboard. But it's a useful hint. Described here: http://stackoverflow.com/a/32261262/1469060

**Comment by DenHeadless** [comment]
Well, that's kinda interesting hack =) I'm not sure that's something i want to support though. The problem with that solution is that table view header is actually `UITableViewCell`. And there can be all sorts of troubles with that, since Apple does not officially support this setup. What would really be best, if they allowed prototyping table view headers, just like they did with UICollectionViews. 

`DTTableViewManager` already supports four kinds of header loading - title headers, headers without XIB, headers from XIB derived from UIView, and headers from XIB derived from UITableViewHeaderFooterView. And while i do want to allow loading headers prototyped in storyboard, this is probably not the way i would want them to be implemented.

One useful trick, though - if you really want to see your table view as on the design, you could design your headers in XIB, and make that class @IBDesignable. Then, if you add that view to storyboard, it could actually render as a part of that UITableViewCell, that represents header.
