### ISSUE TITLE
Carthage Build Errors -- Same Issue 

### ISSUE THREAD

**Issue by wm-j-ray** [DenHeadless/DTTableViewManager#40]
As issue posted under DTModelStorage.  Here is the cartfile portion:

    github "DenHeadless/DTTableViewManager" ~> 4.7.0
    github "realm/realm-cocoa"

**Comment by DenHeadless** [comment]
As stated in https://github.com/DenHeadless/DTModelStorage/issues/12, you can remove "realm/realm-cocoa" line from Cartfile, since this dependency is installed automatically. If you will continue to receive build errors, please reopen this issue and post a build log, we'll investigate more. At least on my machine following Cartfile:

```
github "DenHeadless/DTTableViewManager" ~> 4.7.0
```

installs correctly.
