### ISSUE TITLE
How to use sectionForSectionIndexTitle

### ISSUE THREAD

**Issue by Emptyless** [DenHeadless/DTTableViewManager#47]
Normally you conform to UITableViewDataSource and you can add the function like: 

sectionForSectionIndexTitle and sectionIndexTitlesForTableview. 

However conforming to the UITableViewDataSource results in having to add all the functions like cellForRow and numberOfSections etc which break the manager acting as datasource/manager. How can I can i still call the manager to display the indexTitles? 

I am using CoreData with a fetchResultController and have a keyPath (firstLetter) to assign to each sectionHeader.

**Comment by DenHeadless** [comment]
Oh well. It seems when I was implementing events, this API was forgotten. 

For now you can workaround this by implementing just required bits of `UITableViewDataSource` protocol on your UIViewController like so:

```swift
func numberOfSections(in tableView: UITableView) -> Int {
    return manager.numberOfSections(in: tableView)
}

func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
    return manager.tableView(tableView, numberOfRowsInSection: section)
}

func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
    return manager.tableView(tableView, cellForRowAt: indexPath)
}
```

In the future I think we should have block-based events for those two methods similar to other events. I will leave this issue open, because API is not there yet.

**Comment by Emptyless** [comment]
Thanks for looking into it, thought I made a silly mistake by not founding it.
